### ISSUE TITLE
AttributeError: Cannot find field 'pred_keypoints' in the given Instances!

### ISSUE THREAD

**Issue by evan4C** [maxfrei750/FibeR-CNN#1]
Hello
I was trying to run the demo but it shows the following error:

code:

```
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/demo/demo.py", line 50, in <module>
    demo()
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/demo/demo.py", line 42, in demo
    outputs = predictor(image)
  File "/Users/fan/Downloads/detectron2/detectron2/engine/defaults.py", line 223, in __call__
    predictions = self.model([inputs])[0]
  File "/Users/fan/opt/anaconda3/envs/fiberAnalysis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/fan/Downloads/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 149, in forward
    return self.inference(batched_inputs)
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/model.py", line 50, in inference
    results = self._postprocess2(results)
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/model.py", line 62, in _postprocess2
    instances = perform_keypoint_pruning(
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/postprocessing.py", line 43, in perform_keypoint_pruning
    keypoint_sets = instances.pred_keypoints
  File "/Users/fan/Downloads/detectron2/detectron2/structures/instances.py", line 65, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'pred_keypoints' in the given Instances!

Process finished with exit code 1
```
My environment is built on Mac, but I can run the official demo correctly by cpu only.
Please help me look into this!

**Comment by maxfrei750** [comment]
Hi there!

> My environment is built on Mac

Just to make sure that it is not related to detectron2, did you install according to https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md?

> I can run the official demo correctly by cpu only

So on the CPU, everything works fine but on the GPU you get this error?

> in perform_keypoint_pruning

What happens when you disable keypoint pruning in `demo/config.yaml`?

Do you use the supplied `test-image.png`or do you use an image of your own?

**Comment by evan4C** [comment]
1. Sure, I followed the official installation tutorial. 
2. Actually, I also ran this demo on the CPU by adding one line code after the Load config block.

```
# Load config.
    config = get_fibercnn_config()
    config.merge_from_file(config_filename)

    config.MODEL.DEVICE = 'cpu'
```

3. It seems nothing changed when I disabled keypoint pruning like this:
```
POSTPROCESSING:
    KEYPOINT_PRUNING:
      ENABLED: false
```

4. I am using the default test image. 

And by the way, when I first ran the demo without any modification, I got the following error:

```
Traceback (most recent call last):
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/demo/demo.py", line 50, in <module>
    demo()
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/demo/demo.py", line 36, in demo
    predictor = get_predictor(config)
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/evaluation/utilities.py", line 28, in get_predictor
    predictor = DefaultPredictor(config)
  File "/Users/fan/Downloads/detectron2/detectron2/engine/defaults.py", line 188, in __init__
    self.model = build_model(self.cfg)
  File "/Users/fan/Downloads/detectron2/detectron2/modeling/meta_arch/build.py", line 21, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/model.py", line 16, in __init__
    super().__init__(cfg)
  File "/Users/fan/Downloads/detectron2/detectron2/config/config.py", line 181, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/Users/fan/Downloads/detectron2/detectron2/config/config.py", line 236, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/Users/fan/Downloads/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 79, in from_config
    "roi_heads": build_roi_heads(cfg, backbone.output_shape()),
  File "/Users/fan/Downloads/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
    return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/roi_head.py", line 25, in __init__
    self._init_fiber_roi_heads(cfg)
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/roi_head.py", line 29, in _init_fiber_roi_heads
    self._init_fiber_width_head(cfg)
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/roi_head.py", line 37, in _init_fiber_width_head
    pooler_scales = [1.0 / self.feature_strides[k] for k in self.in_features]
  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/roi_head.py", line 37, in <listcomp>
    pooler_scales = [1.0 / self.feature_strides[k] for k in self.in_features]
  File "/Users/fan/opt/anaconda3/envs/fiberAnalysis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'FiberROIHeads' object has no attribute 'feature_strides'
```

And then I solved this by adding the following two lines in the roi_head.py.

```
 self.feature_strides = {k: v.stride for k, v in input_shape.items()}
 self.feature_channels = {k: v.channels for k, v in input_shape.items()}
```

After that, the first error happened and I have no idea how to handle it.

**Comment by maxfrei750** [comment]
> And by the way, when I first ran the demo without any modification, I got the following error:
> 
> ```
> Traceback (most recent call last):
>   File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/demo/demo.py", line 50, in <module>
>     demo()
>   File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/demo/demo.py", line 36, in demo
>     predictor = get_predictor(config)
>   File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/evaluation/utilities.py", line 28, in get_predictor
>     predictor = DefaultPredictor(config)
>   File "/Users/fan/Downloads/detectron2/detectron2/engine/defaults.py", line 188, in __init__
>     self.model = build_model(self.cfg)
>   File "/Users/fan/Downloads/detectron2/detectron2/modeling/meta_arch/build.py", line 21, in build_model
>     model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
>   File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/model.py", line 16, in __init__
>     super().__init__(cfg)
>   File "/Users/fan/Downloads/detectron2/detectron2/config/config.py", line 181, in wrapped
>     explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
>   File "/Users/fan/Downloads/detectron2/detectron2/config/config.py", line 236, in _get_args_from_config
>     ret = from_config_func(*args, **kwargs)
>   File "/Users/fan/Downloads/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 79, in from_config
>     "roi_heads": build_roi_heads(cfg, backbone.output_shape()),
>   File "/Users/fan/Downloads/detectron2/detectron2/modeling/roi_heads/roi_heads.py", line 43, in build_roi_heads
>     return ROI_HEADS_REGISTRY.get(name)(cfg, input_shape)
>   File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/roi_head.py", line 25, in __init__
>     self._init_fiber_roi_heads(cfg)
>   File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/roi_head.py", line 29, in _init_fiber_roi_heads
>     self._init_fiber_width_head(cfg)
>   File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/roi_head.py", line 37, in _init_fiber_width_head
>     pooler_scales = [1.0 / self.feature_strides[k] for k in self.in_features]
>   File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/roi_head.py", line 37, in <listcomp>
>     pooler_scales = [1.0 / self.feature_strides[k] for k in self.in_features]
>   File "/Users/fan/opt/anaconda3/envs/fiberAnalysis/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
>     raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
> torch.nn.modules.module.ModuleAttributeError: 'FiberROIHeads' object has no attribute 'feature_strides'
> ```
> 
> And then I solved this by adding the following two lines in the roi_head.py.
> 
> ```
>  self.feature_strides = {k: v.stride for k, v in input_shape.items()}
>  self.feature_channels = {k: v.channels for k, v in input_shape.items()}
> ```

This error results from a change in detectron2 in release 0.1.2 (see https://github.com/facebookresearch/detectron2/releases/tag/v0.1.2). That's why I locked down the version of detectron in https://github.com/maxfrei750/FibeR-CNN/blob/master/environment.yaml. Unfortunately, I forgot to also change the readme accordingly. I just fixed that in 14c3a05. Thanks for bringing that to my attention.

So please adjust your environment accordingly, to rule that out as a source of error.

Concerning the original error message:
> ...
>  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/model.py", line 62, in _postprocess2
>    instances = perform_keypoint_pruning(
>  File "/Users/fan/Documents/GitHub/DeepLearning/FibeR-CNN/fibercnn/modeling/postprocessing.py", line 43, in perform_keypoint_pruning
>   keypoint_sets = instances.pred_keypoints
> ...

The error occurs in `perform_keypoint_pruning`, which is not executed if `POSTPROCESSING.KEYPOINT_PRUNING.ENABLED = False` (I just double-checked that). So the error should not occur if you disabled keypoint pruning correctly. However, `instances.pred_keypoints` should definitively exist. So something else must be wrong. Maybe it is connected to the version differences, so please test that out first and keep me updated.

**Comment by evan4C** [comment]
Thanks a lot for your prompt replies! It works fine after I changed the detectron2 version! 

Although the accuracy is poor when I changed the demo image to my test image, where a lot of fibers are tangled. I'll make out if it can be improved by my own dataset.

**Comment by maxfrei750** [comment]
Nice! Glad I could help. 

>Although the accuracy is poor when I changed the demo image to my test image, where a lot of fibers are tangled. I'll make out if it can be improved by my own dataset.

Retraining might very well improve the results drastically. Depending on the number of fibers per image, it might also be necessary to tweak the config.
